version: '3.5'

services:

  api:
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    build:
      context: .
      dockerfile: "dockerfile.ConfigAPI"
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    command: 'python main.py'

